dubbo:
  application:
    name: dubbo-service
  scan:
    base-packages: org.dubbo.service.impl
  registry:
    address: nacos://localhost:8848

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monaco?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password:
    hikari:
      minimumIdle: 1
      idleTimeout: 60000